language: node_js
node_js:
- stable
notifications:
  slack:
    rooms:
      secure: iDvzpHkbW7pooU0XdRAG2A9unCbWDB6PwJY0KwVAiawI5uHZHQeRToaiifbCBbSsXv4IWfGIytmg4ufKhE/BrVw1GLeiWWujsfuIKoY0tBPlamawhH8gulMH2AbggWIXVz5oBq37i80Z45DXENx0FkSl9szzx+HU0U9D7+aVWppGQcAvyN7Ih93ZDBPyEhV/hIw9NMFQuRFn96n0QE1gxAdCMnngkJ0aujTN0CoCcIAJYTkzaae4B27SQJ8C9n3JLjOxq7Q5trW9cCtGSRjlnver8xIRlQr34ScQxHlJahuuufM4MM1lCKzRLSxn7uHvauy+KyArRuuMCNue/CxsO8e6uAgPpJqC3OIXRqpjo7kvigjZgoTTdKLEUcjz/U+O7pKAy04IInZ5xBayi1oExER4vgxs3zGHgC/MRy+K/ZAPETz2KAEhzDURi+sKNxwjM8B/S6WMTo9ZM1VFvYoDBRV+B0UR5Cwno6rQZi+C7Hd2bOxL9wu8BL9Q5tcjjtjk9+skM4ZkrFZDrwcLbuwOpgrTxiGNH/NOLZj5z/lTZPA9UCWhCfud9f7f7Q2b2FYFL7c8zVgztLGjXRPR3QPLNRk2PRDR93gzbYIGeRKpLl3F47g7ogvURc5jVXQwiD0NOOjLHbLjCXxX7RU7YdAyBMGBvKec6Cb9BrXjEgbFU2U=
